=== moustafaHegazyJETS/JavaSEProject/Server UI/converstaion/chat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="Chat" type="chatType"/>

<!--chat type-->
<xs:complexType name="chatType">
	<xs:sequence>
		<!--<xs:element name="Messages" type="MsgsType" maxOccurs="1"/>-->
		<xs:element name="Message" type="MsgType" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<!--MessagesType-->
<!--
<xs:complexType name="MsgsType">
	<xs:sequence>
		<xs:element name="Message" type="MsgType" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>
-->
<!--Message Type-->
<xs:complexType name="MsgType">
	<xs:sequence>
		<xs:element name="Sender" type="SenderType"/>
		<xs:element name="Receiver" type="ReceiverType"/>
	</xs:sequence>
	<xs:attribute name="color" type="xs:string"/>
	<xs:attribute name="font" type="xs:string"/>
</xs:complexType>

<!--Sender Type-->
<xs:complexType name="SenderType">
	<xs:simpleContent>
		<xs:extension base="xs:string">
			<xs:attribute name="id" type="xs:integer"/>
		</xs:extension>
	</xs:simpleContent>
</xs:complexType>

<!-- ReceiverType -->
<xs:complexType name="ReceiverType">
	<xs:attribute name="id" type="xs:integer"/>
</xs:complexType>

</xs:schema>

=== moustafaHegazyJETS/JavaSEProject/Server UI/converstaion/omarH_null.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><?xml-stylesheet type='text/xsl' href='history.xsl'?>
<Chat xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="chat.xsd">
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="64">hiiiiiiiii</Sender>
        <Receiver id="2067"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="64">azik ya homar</Sender>
        <Receiver id="2067"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="2067">ya 5ara </Sender>
        <Receiver id="64"/>
    </Message>
</Chat>

=== moustafaHegazyJETS/JavaSEProject/Server UI/converstaion/AhmedMazen_beshoy.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><?xml-stylesheet type='text/xsl' href='history.xsl'?>
<Chat xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="chat.xsd">
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="64">moustafa</Sender>
        <Receiver id="62"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="64">salma</Sender>
        <Receiver id="62"/>
    </Message>
    <Message color="rgb(153,51,0)" font="Impact">
        <Sender id="62">moustafa respond</Sender>
        <Receiver id="64"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="67">salma</Sender>
        <Receiver id="64"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="1071">moustafabeshoy</Sender>
        <Receiver id="63"/>
    </Message>
    <Message color="rgb(153,51,0)" font="Impact">
        <Sender id="62">moustafa</Sender>
        <Receiver id="63"/>
    </Message>
    <Message color="rgb(153,51,0)" font="Impact">
        <Sender id="62">ssahsahsa</Sender>
        <Receiver id="63"/>
    </Message>
    <Message color="rgb(153,51,0)" font="Impact">
        <Sender id="62">assasasa</Sender>
        <Receiver id="63"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="64">moustafa</Sender>
        <Receiver id="62"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="1071">hegazy</Sender>
        <Receiver id="63"/>
    </Message>
</Chat>

=== moustafaHegazyJETS/JavaSEProject/Server UI/converstaion/omarH_salma.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><?xml-stylesheet type='text/xsl' href='history.xsl'?>
<Chat xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="chat.xsd">
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="64">hiiiiiiiii</Sender>
        <Receiver id="2067"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="64">azik ya homar</Sender>
        <Receiver id="2067"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="2067">ya 5ara </Sender>
        <Receiver id="64"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="64">sa7</Sender>
        <Receiver id="2067"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="64">hiiiii</Sender>
        <Receiver id="2067"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="64">mm</Sender>
        <Receiver id="2067"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="2067">ddssaas</Sender>
        <Receiver id="64"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="64">sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss</Sender>
        <Receiver id="2067"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="2067">sdsdds</Sender>
        <Receiver id="64"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="2067">sd</Sender>
        <Receiver id="64"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="2067">ds</Sender>
        <Receiver id="64"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="2067">ds</Sender>
        <Receiver id="64"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="2067">ds</Sender>
        <Receiver id="64"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="2067"></Sender>
        <Receiver id="64"/>
    </Message>
</Chat>

=== moustafaHegazyJETS/JavaSEProject/Server UI/converstaion/beshoy_salma.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><?xml-stylesheet type='text/xsl' href='history.xsl'?>
<Chat xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="chat.xsd">
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="64">hiiiiiiiii</Sender>
        <Receiver id="63"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="63">hehe</Sender>
        <Receiver id="64"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="63">msouaasvdsha</Sender>
        <Receiver id="64"/>
    </Message>
</Chat>

=== moustafaHegazyJETS/JavaSEProject/Server UI/converstaion/salma_moustafa.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><?xml-stylesheet type='text/xsl' href='history.xsl'?>
<Chat xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="chat.xsd">
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="62">hello Salma</Sender>
        <Receiver id="64"/>
    </Message>
    <Message color="rgb(0,51,51)" font="Arial Black">
        <Sender id="62">moustafa</Sender>
        <Receiver id="64"/>
    </Message>
    <Message color="rgb(0,51,51)" font="Arial Black">
        <Sender id="62">moustafa</Sender>
        <Receiver id="64"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="64">moustafa</Sender>
        <Receiver id="62"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="64">ssss</Sender>
        <Receiver id="62"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="64">assdsa</Sender>
        <Receiver id="62"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="64">moudg</Sender>
        <Receiver id="62"/>
    </Message>
</Chat>

=== moustafaHegazyJETS/JavaSEProject/Server UI/converstaion/moustafa_Menem.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><?xml-stylesheet type='text/xsl' href='history.xsl'?>
<Chat xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="chat.xsd">
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="64">a</Sender>
        <Receiver id="62"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="64">adaas</Sender>
        <Receiver id="62"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="62">khjhk</Sender>
        <Receiver id="64"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="62">jbjb</Sender>
        <Receiver id="64"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="62">kk</Sender>
        <Receiver id="64"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="65">knlkm</Sender>
        <Receiver id="62"/>
    </Message>
    <Message color="rgb(255,255,255)" font="Arial Black">
        <Sender id="62">jjkjk</Sender>
        <Receiver id="65"/>
    </Message>
</Chat>
